### ISSUE TITLE
Hardcoded Pfade entfernen

### ISSUE THREAD

**Issue by NoFear23m** [flori2212/EnergieverbrauchDerSchule#10]
Wie schon angesprochen bitte die Hardcoded-Pfade entfernen. Ist nun mal ein no-go.

`Service.DataService.Instance.XmlFolderPath = "C:\Users\flori\Desktop\ExampleFiles"`

**Comment by flori2212** [comment]
Die Hardcorepfade wurden entfernt

-Florian
