### ISSUE TITLE
Kompletten Namen Abändern

### ISSUE THREAD

**Issue by flori2212** [flori2212/EnergieverbrauchDerSchule#11]
Hallo,

kannst du eventuell den Namen des Projekts auf "Energievebrauch der Schule" ändern, ich hab es schon überall gemacht, aber der Ordner z. B. heißt noch immer ConsumerBeispiel

-Florian

**Comment by NoFear23m** [comment]
Soweit ich weis kann der Ordnername nach einem Commit nicht mehr geändert werden. Ich bekomme zumindest ne Medung das der Zugriff verweigert wird. Vermutlich wird es durch Git gesperrt. 
Ist aber im Grunde egal wie der Ordner heißt oder? Sieht später niemand wenn das Program ausgerollt wird.

**Comment by flori2212** [comment]
Ach so, ok.

-Florian
