### ISSUE TITLE
Welches Framework

### ISSUE THREAD

**Issue by flori2212** [flori2212/EnergieverbrauchDerSchule#12]
Hallo,
das Projekt ist ja aktuell auf dem .Net Framework 4.6.2
Kann ich auch auf 4.0 runtergehen. Das Programm sollte auch auf einem Windows 7 PC laufen und da ist, wie ich glaube, nur .Net Framework 4 vorinstalliert.

-Florian

**Comment by NoFear23m** [comment]
Und nur weil ein Framework "vorinstalliert" ist bedeutet das das man nicht darüber Entwickeln kann?
Schau mal hier: https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements
Bis .Net 4.8 wird alles unter Windows 7 unterstützt. Weiter runter wie 4.5 würde ich auf keinen Fall gehen.

Grüße

**Comment by flori2212** [comment]
Ich sehe da, bei Windows 7 ist gar kein .Net framework installiert?
Ich kann auf dem PC nämlich nichts installieren.

-Florian

**Comment by NoFear23m** [comment]
Wie, du kannst nichts installieren. Haste die Freigabe von deiner Schule nicht?
Musst du in der Schule nachsehen was da für ein Framework drauf ist. Das steht nur das nicht installiert ist weil es auf die Installation bei Win 7 ankommt. In den Win 7 Features kann/konnte man glaube ich wählen ob man .NET 4 oder 4.5 drauf haben wollte bzw. .Net 4.5 direkt aus dem Featurekatalog nachinstallieren. Musste mal gucken bei dir in der Schule.

**Comment by flori2212** [comment]
Schaue ich mal morgen, was da installiert ist.
Hoffentlich 4.5

-Florian

**Comment by flori2212** [comment]
Klappt auf dem PC

-Florian
