### ISSUE TITLE
Filter bei vielen Einträgen sehr langsam

### ISSUE THREAD

**Issue by flori2212** [flori2212/EnergieverbrauchDerSchule#3]
Leider hat deine Verbesserung nichts gebracht.
Der Filter braucht, wenn ich einen Buchstaben eingebe ca. 2 Sekunden bis er die View aktualisiert

Wenn der Buchstabe allerdings kein Ergebnis liefert, wird er ohne Verzögerung eingegeben

-Florian

**Comment by NoFear23m** [comment]
Bitte die XMLs mit den Beispieldaten mal hochladen. Danke

**Comment by flori2212** [comment]
[ExampleFiles.zip](https://github.com/flori2212/EnergieverbrauchDerSchule/files/3144769/ExampleFiles.zip)

Bitteschön.

-Florian

**Comment by NoFear23m** [comment]
Das Problem war nicht das der Filter langsam war. Die View war es. Durch das Grouping hat die RowVirtualisierung des intern für das DataGrid verwendetem VirtualizingStackPanel nicht mehr funktioniert. Seit .Net 4.5 gibt es aber die Eigenschaft "IsVirtualizingWhenGrouping". Setzt man diese auf True funktioniert es wieder.

Grüße

**Comment by flori2212** [comment]
Da muss man aber erstmal drauf kommen.
Super, vielen Dank

-Florian

**Comment by NoFear23m** [comment]
Ja, der richtige Hinweis war das es nicht lange dauert wenn er nix findet. In dem Fall durchläuft er im Filter aber auch ALLE Items. Also musste die View langsam sein.
