### ISSUE TITLE
Calculate - Wirft sicher NullReferenceException

### ISSUE THREAD

**Issue by NoFear23m** [flori2212/EnergieverbrauchDerSchule#5]
Hallo

In CalculateService in Zeile 23 wird die Variable timeArea definiert aber nicht instanziiert.

In zeile 43 wird sie dann verwendet, aber nirgens instanziiert? Das gibt sicher ne NullRefernceException!

Das selbe für "deviceGroup" und "device"!!

**Comment by flori2212** [comment]
Hallo

du hast recht, allerdings funktioniert die Funktion, da ich den Objekten in den For Each Schleifen (s. Z. 25-29) schon etwas zuweise.
Ist aber unsicher, ich behebe es.

-Florian

**Comment by flori2212** [comment]
Gut, ich lasse die Objekte gleich inistalisieren, dann gibt es sicher keine NulReferenceException

**Comment by NoFear23m** [comment]
Setzt er den Wert nicht weil es vieleicht keines mit der ID gibt knallt es in Zeile 43.

Weiters vieleicht die Benennungsregeln und Typos: 

KwhByDeviceGroups statt kWhByDeviceGroups
KwhPerYear statt kWhPerYeahr
PricePerYear statt PricePerYeahr (Vieleicht ist CostPerYear sogar besser)

Sub immer mit erstem Buchstaben groß bitte, sonst merkert mein VS oooohne ende:
Also "NewConsusmer" statt "newConsumer"

Grüße
![Errors](https://user-images.githubusercontent.com/15660141/57184464-46aa8c80-6ebc-11e9-96ac-6c1b6b28c331.PNG)
