### ISSUE TITLE
Fehler beim öffnen des Fensters "add_consumer"

### ISSUE THREAD

**Issue by flori2212** [flori2212/EnergieverbrauchDerSchule#8]
Ich habe, wie du gesagt hast, ein ConsumerViewModel angelegt. Wenn ich nun das Fenster aufrufe kommt ein Fehler, dass Value = nothing ist.

Ich habe keine Ahnung, was ich falsch mache

-Florian

**Comment by NoFear23m** [comment]
So, hier das Commit.

Die Datenübergabe an das ViewModel habe ich in den Konstructor vom Fenster geklatscht, ist dort besser aufgehoben. Die Bindung im Fenster war falsch. und der Fehler von den values kahm daher das die Daten falsch übergeben wurde. Du hattest im neuen Consumer-Model-Object nirgens eine ID bei den ganzen Navigations. Also Room, Device usw.

Es MUSS aber ein Wert (per Default auch) vorhanden sein wenn du nicht explizit im Setter auf Nothing prüfst.

Grüße
Sascha

**Comment by flori2212** [comment]
Alles klar, dann hätte ich das auch verstanden. :)
Das nächste mal mache ich es über das Forum.

-Florian
