### ISSUE TITLE
ExampleFiles korrigieren

### ISSUE THREAD

**Issue by NoFear23m** [flori2212/EnergieverbrauchDerSchule#9]
Die Examplefiles sind noch mit Integer-Ids. Bitte für korrekte Testdaten sorgen.

**Comment by flori2212** [comment]
Die neuen Files wurden aktualisiert.

-Florian

**Comment by flori2212** [comment]
Hier sind sie nochmal.

-Florian
[ExampleFiles.zip](https://github.com/flori2212/EnergieverbrauchDerSchule/files/3145473/ExampleFiles.zip)
